backend:
  name: git-gateway
  branch: main
  site_url: https://ipft.studio

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "works"
    label: "Works"
    folder: "content/works"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Year", name: "year", widget: "number" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Medium", name: "medium", widget: "string", required: false }
      - { label: "Size", name: "size", widget: "string", required: false }
